### ISSUE TITLE
Include information as to how to join community meeting

### ISSUE THREAD

**Issue by matoszz** [infratographer/community#20]
It seems as though there's a desire for contributors to join the community meeting but there's no information in the community repo as to how to attend the meeting (is there a dial in? zoom? is it sent out as a part of the mailing list?). I've joined the mailing list but not sure if / when the meeting details are sent out as a part of that, how far in advance they are sent, etc.

Would also be nice to include a link / infos on the slack instance to join in the community repo.

**Comment by andy-v-h** [comment]
There is a zoom link and time in each meeting note. 

It's also described in the readme.

> on the Thursday of [each odd week](https://www.epochconverter.com/weeknumbers) at 10:30 am CT on [Zoom](https://us06web.zoom.us/j/88057942869?pwd=Vnd1OWplazFwREJQeWFHWks4MUptQT09).
